def compress_dxt1(src: bytes, width: int, height: int) -> bytes: ...
def compress_dxt5(src: bytes, width: int, height: int) -> bytes: ...
def decompress_dxt1(src: bytes, width: int, height: int) -> bytes: ...
def decompress_dxt5(src: bytes, width: int, height: int) -> bytes: ...
